### ISSUE TITLE
no app.R file

### ISSUE THREAD

**Issue by yfwang27** [MoriarityLab/MultiEditR#1]
Hi,

I have tried to follow to instruction but still couldn't make it work. I couldn't see the app.R file and I guess it might be the reason that the MultiEditR didn't work for me. Any advice would be very much appreciated. Thank you.

**Comment by MitchellKluesner** [comment]
Hello,

You are correct there is not an app.R file. Instead the app is structured as a directory such that all of the files need to be downloaded to a single directory. Once you do this you can follow the README.txt instructions to run the app.

Does that help?

Mitch

**Comment by yfwang27** [comment]
It works now and thank you very much for the reply.
